name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-java@v2
      name: 자바 설치
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '8'
    - name: application build
      run: ./gradlew clean build -x test
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: docker build
      run: docker build --build-arg JAR_FILE=build/libs/\*.jar -t vsh123/infra-subway .
    - name: docker image pushㄲㄲㄲㄲㄲㄲㄲㄲㄲㄲㄲㄱ
      run: docker push vsh123/infra-subway 
