name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      name: 자바 설치
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '8'
    - name: application build
      run: ./gradlew clean build -x test
